<?php
?>
<div class="form-blog">
    <a href="<?= $block->getUrl('blog/myblog') ?>">Your blog +</a>
    <form action="<?= $block->getUrl('blog/action/save') ?>" class="form" method="POST" enctype="multipart/form-data" id="form-add-blog" data-mage-init='{"validation": {}}'>
        <div class="form-group">
            <label for="">Title</label>
            <input type="text" placeholder="Enter title" name="title" id="title" class="form-control" data-validate="{'required-entry':true}">
            <small class="erTitleEl elErr"></small>
        </div>
        <br>
        <div class="form-group">
            <label for="">Content</label>
            <textarea name="content" id="content" cols="30" rows="5" data-validate="{'required-entry':true}"></textarea>
        </div>
        <br>
        <div class="form-group">
            <label for="">Url key</label>
            <input type="text" placeholder="Enter url" name="url_key" id="url_key" class="form-control" data-validate="{'required-entry':true}">
        </div>
        <br>
        <div class="form-group">
            <label for="">Feature image</label>
            <input type="file" class="form-control" name="featured_image" id="featured_image" data-validate="{'required-file':true}">
            <img src="" id="img-preview" />
        </div>
        <br>
        <div class="form-group">
            <label for="">Status</label>
            <select name="status" id="status">
                <option value="1">Publish</option>
                <option value="2">Draft</option>
                <option value="3">Non-Publish</option>
            </select>
        </div>
        <br>
    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>"/>
        <button type="submit" id="btn-add-blog">Submit</button>
    </form>
</div>

<script>
    require(["jquery",'mage/url'],function ($,urlBuilder){
        $(document).ready(function (){

            $('#form-add-blog').mage('validation',{
                submitHandler:function(form){

                    if($('input[name="content"]').val() == '' || $('input[name="url_key"]').val() ){
                        $('.erTitleEl').html('');
                        $('input[name="title"]').css('border','');
                    }

                    const url = urlBuilder.build('blog/ajax/validate');
                    const title = $('input[name="title"]').val();
                        $.ajax({
                            //    gui form data -> controller
                            url: url,
                            type:'POST',
                            dataType :'json',
                            data:{
                                title:title
                            },
                            success:function(res){

                                if(res.status == 'exist'){
                                    $('.erTitleEl').html('Title existed! please again!');
                                    $('input[name="title"]').css('border','solid red');
                                }else{
                                    // not exist -> submit save blog
                                   form.submit();
                                }
                            },
                            error(err){
                                console.log(err)
                            }
                        })
                }
            })

        })
    })

</script>
