<?php
//    $blog = $block->getBlog(1);
    $blogs = $block->getBlogCollection();
    $blog = $block->getBlog();
//    $getJoinAuthor = $block->getAll();
//    echo "<pre>";
//    var_dump($getJoinAuthor);
//    die;
?>

<div class="wrapper bg-pink p-3">

    <div class="container">
        <div class="sidebar">
            <h4>Menu blog</h4>
            <?php foreach($blogs as $val): ?>
                <p><a href="<?= $this->getUrl('blog/detail?id='.$val->getData('id')) ?>" class="nav-link"><?= $val->getData('title') ?></a></p>
            <?php endforeach;?>
        </div>
        <small class="content">
            <h3><?= $blog['title'] ?></h3>
            <div><?= $blog['content'] ?></div>
            <div>
                <img src="<?= $blog['featured_image'] ?>" width="80px"/>
            </div>
            <br>
            <small><?= $blog['author_id'] ?></small>
        </div>
    </div>
</div>
