<?php
    $blogList = $block->getBlogList();
?>

<div class="list-blog">
    <h3>List blog Ecommage</h3>
    <ul>
        <?php if($blogList->getData()){
            foreach($blogList as $key=>$blog) {
        ?>
            <li>
                <a href="<?= $this->getUrl('blog/detail/index/id/'.$blog->getData('id')) ?>" >
                    <?= $blog->getData('title') ?>
                    <span> - Author: <?= $blog->getData('author_id') ?></span>
                </a>
            </li>
        <?php }}else
            echo "nothing!";
        ?>
    </ul>
</div>
