<?php
$slider = $block->getSliderItems();
$mediaUrl = $block->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>

<h1 style="color:chartreuse">Slider of blog</h1>

<!--use swiper || slick slider display-->
<div class="slick-slider">

    <?php if($slider->getSize()){ foreach($slider as $item){ ?>

    <a class="item" href="<?= $block->getUrl('blog/detail/index/id/'.$item->getData('id')) ?>" class="slider-item" style="background:#ccc; padding: 10px;">
        <div style="height: 200px; width: 200px; object-fit: cover; "><img src="<?= $mediaUrl.$item->getData('featured_image') ?>" alt="" width="100%" height="100% !important;"></div>
        <h5><?= $item->getData('title') ?></h5>
        <small>Author name: hiep</small>
    </a>

    <?php }}else echo 'nothing!'; ?>
</div>
