

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
	<div class="wrapper bg-pink p-3" style="background: #ccc; padding: 10px 20px;">
		<h2>Form member registration </h2>
       <form action="" method="post">
           <div class="form-group">
               <input type="text" name="name" placeholder="Enter your name" class="form-control" required>
           </div>
           <div class="form-group">
               <input type="email" name="email" placeholder="Enter your email @" class="form-control" required>
           </div>
           <button type="submit" class="text-primary">Sumit</button>
       </form>
	</div>


</body>
</html>