

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
	<div class="wrapper bg-pink p-3">
		<h2><?= $block->getTitle() ?> </h2>

        <div style="color:blue;"></div>

        <div style="color:red;"><?php foreach($block->getMyInfo() as $key=>$item){
                    echo $key.': '.$item.'<br>';
            }  ?></div>
	</div>

</body>
</html>
