

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
	<div class="wrapper bg-pink p-3" style="background: #ccc; padding: 10px 20px;">
		<h2>View Blog Ecommage </h2>
        <ul class="nav-link">
            <li><a href="/helloworld">hello world</a></li>
            <li><a href="#">Bong da</a></li>
            <li><a href="#">Bong da</a></li>
            <li>Thoi trang</li>
            <li>Thoi tiet</li>
        </ul>
	</div>


</body>
</html>